name: Validate latest compatibility

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  pull_request: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions:
        contents: read
        pages: write
        id-token: write
    steps:
        - name: Check out source repository
          uses: actions/checkout@v2

        - uses: darklab8/infra/.github/actions/checkout-freelancer@master
          with:
            freelancer-mod: "vanilla"
            freelancer-folder: ${{ github.workspace }}/freelancer_folder
            ssh-key-base64-vanilla: ${{ secrets.ID_RSA_FILES_FREELANCER_VANILLA }}

        - name: Set up Go
          uses: darklab8/infra/.github/actions/install-go@master
        
        - name: Install flsr patcher
          run: go install github.com/darklab8/fl-data-flsr@latest
        - name: Install latest darkstat
          uses: darklab8/fl-darkstat/.github/actions/install-latest@master
        - name: validate
          run: darkstat --map-on --stat-deals-on validate error
          env:
            CONFIGS_FREELANCER_FOLDER: ${{ github.workspace }}/Freelancer
            CONFIGS_FREELANCER_FOLDER_FAILBACK: ${{ github.workspace }}/freelancer_folder

        # # in case you ever decide writing pipeline to deploy to dev pages instead. Remove working from pull requests then.
        # - uses: darklab8/fl-darkstat/.github/actions/build@master
        #   if: github.ref == 'refs/heads/main' 
        #   with:
        #     site-root: "/FLSR/"
        #     freelancer-folder: ${{ github.workspace }}/freelancer_folder
        #     heading: <a href="https://github.com/darklab8/fl-darkstat">Darkstat</a> from <a href="https://darklab8.github.io/blog/pet_projects.html#Freelancercommunity">DarkTools</a> for <a href="https://github.com/darklab8/fl-data-flsr">FLSR</a> of <a href="https://github.com/Freelancer-Sirius-Revival/FLSR/commit/${{ github.sha }}">PREVIEW ${{ github.sha }}</a>
        #     command: --stat-deals-on build
        #     map-on: "true"
        #     map-index-url: map.html
        #     disable-dev-mode: "false"

        # - uses: actions/upload-pages-artifact@v3
        #   if: github.ref == 'refs/heads/main' 
        #   with:
        #     name: github-pages
        #     path: ./build
        # # Turn on ability to deploy to pages in repository settings, Pages tab
        # # choose "Github Actions" deployment method to Pages
        # - name: Deploy to pages
        #   uses: actions/deploy-pages@v4
        #   id: deployment
        #   continue-on-error: true
