name: Validate latest compatibility

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  pull_request: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    permissions:
        contents: read
        pages: write
        id-token: write
    steps:
        - name: Check out source repository
          uses: actions/checkout@v2
        - uses: darklab8/infra/.github/actions/checkout-freelancer@master
          with:
            freelancer-mod: "vanilla"
            freelancer-folder: ${{ github.workspace }}/freelancer_folder
            ssh-key-base64-vanilla: ${{ secrets.ID_RSA_FILES_FREELANCER_VANILLA }}

        - name: Set up Go
          uses: darklab8/infra/.github/actions/install-go@master
        
        - name: Install flsr patcher
          run: go install github.com/darklab8/fl-data-flsr@latest
        - name: Install latest darkstat
          uses: darklab8/fl-darkstat/.github/actions/install-latest@master
        - name: validate
          run: darkstat --map-on --stat-deals-on validate error
          env:
            CONFIGS_FREELANCER_FOLDER: ${{ github.workspace }}/Freelancer
            CONFIGS_FREELANCER_FOLDER_FAILBACK: ${{ github.workspace }}/freelancer_folder
